---
title: "Homework_09"
author: "Franny Oppenheimer"
date: "2024-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br/>

##### Creating a fake dataset using Mean Unique Units per Cycle

```{r}

# purposefully NOT making this a function because I want these variables to be accessible later

library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation
library(dplyr)
  
# Read in data
z <- read.csv("Allen et al - Proceedings B Supplementary Data - Raw Data 3.csv",header=TRUE,sep=",")
z$myVar <-z$Mean.Unique.Units.per.Cycle
summary(z)

# Generate relevant summary statistics from data
normPars <- fitdistr(z$myVar,"normal")
print(normPars) #
str(normPars)

zMean <- normPars$estimate["mean"] 
zMean
zSD <- normPars$estimate["sd"] 
zSD
# Using data from Allen et al., 2018 - mean unique units per cycle

# Generate random normal data with the mean and sd from that dataset
mean <- rnorm(n=3,mean=zMean,sd=zSD)
mean
year <- c("2002","2003","2004")
sd <- runif(3)

# make that normal data into a data frame
normz <- data.frame(year,mean,sd)
print(normz)

```

<br/>

##### Conducting an ANOVA on my fake dataset

```{r}

# setting up one-way ANOVA - just the first 3 years

# Global Variables

nGroup <-  3
nName <- c("2002","2003","2004") # names of groups
nSize <- c(1,1,1) # number of observations in each group
nSize
nMean <- mean[1:3]
nMean
nSD <- sd
nSD

# function to make a res_var data frame 

getanodata <- function(n_size,nMean,nSD) {
  
  res_var <- data.frame(matrix(nrow=3,ncol=4))
  colnames(res_var) <- c("year","n","value","sd")
  
  for (i in 1:3) {
 
  res_var[i,] <- c(nName[i],nSize[i],nMean[i],nSD[i])
    
  }
  
  return(res_var)
}

res_var <- getanodata(nSize,nMean,nSD)
# res_var <- rep(res_var[,1:3],nSize) # year, n, mean, sd
res_var <- data.frame(res_var)
res_var

year <- res_var[1,]
value <- res_var[,3]


# actual ANOVA! Doing ANOVA between years
anova <- aov(value ~ year,data=res_var)
print(anova)

z <- summary(anova)
print(z)

# plot
ano_plot <- ggplot(anova) +
            aes(year,mean) +
            geom_boxplot()

print(ano_plot)
# I only have 1 mean per year so it looks weird

```

<br/>

##### Making a Bar Plot (and calculating the median to build it)

```{r}

library(ggplot2)

res_var <- getanodata(nSize,nMean,nSD)
res_var

BarPlot <- function(res_var) {

  barplotdata <- data.frame(matrix(nrow=3,ncol=4))
  colnames(barplotdata) <- c("year","mean","sd","median")
  
  
  for (i in 1:3) {
  
   barplotdata[i,"year"] <- as.numeric(res_var[i,1])
    
   barplotdata[i,"mean"] <- as.numeric(res_var[i,3]) # already a mean in the dataset given, no need to calculate it
    
   barplotdata[i,"sd"] <- as.numeric(res_var[i,4])
    
   barplotdata[i,"median"] <- normPars$estimate["median"]
  
  }
   
   BarChart <- ggplot(data=barplotdata,
                       aes(year,mean))+geom_boxplot(aes(
                         group=year,
                         lower=(barplotdata[i,2]-barplotdata[i,3]),
                         upper=(barplotdata[i,2]+barplotdata[i,3]),
                         middle=barplotdata[i,4],
                         ymin=(barplotdata[i,2]-3*barplotdata[i,3]),
                         ymax=(barplotdata[i,2]+3*barplotdata[i,3])))

return(print(BarChart))
  
}

BarPlot(res_var)

# again, only 1 mean per year (looks weird!)
```
