---
title: "Homework_11"
author: "Franny Oppenheimer"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br/>

##### Get Barracudar ready

```{r}
# load packages ----
# load packages ----
library(log4r)
library(TeachingDemos)
library(tidyverse)
library(pracma)
library(ggmosaic)
library(stringr)
# load any additional packages here...


# source function files ----

setwd("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar")

source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/DataTableTemplate.R")
source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/AddFolder.R")
source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/BuildFunction.R")
source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/MetaDataTemplate.R")
source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/CreatePaddedLabel.R")
source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/InitiateSeed.R")
source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/SetUpLog.R")
source("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/barracudar/SourceBatch.R")

setwd("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/OriginalData")

```

<br/>

##### Question 2

```{r}
# gathering the file names that we actually want to look at in a vector called filenames

# list.files() will gather character strings of file names

filelist <- list.files("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/OriginalData",pattern="BART")

# use a for loop for number of files that we're concerned with, pull out files

# paste() or paste0() function concatenates strings
# paste0("Here is ","the ","filepath: ", filelist[1]) # example

# make an empty vector
filenames <- c()

# make matrix of file names
for (i in 1:10) {
  setwd(paste0("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/OriginalData","/", filelist[i])) # create new file path to go to

  filenames[i] <- list.files(pattern="countdata") # any time the file has "countdata" in it, it pulls it out
}

filenames

```

<br/>

##### Questions 3 & 4

```{r}
# generating functions to get rid of empty/missing cases, extract the year from the file name, calculate total number of individuals found, and calculate number of unique species found


getinfo <- function(filelist,filenames) {

  metadata <- matrix(0,length(filelist),4)
  colnames(metadata) <- c("File","Year","Total # Individuals", "Species Richness")

  for (i in 1:10) { # for every folder (there is only one good csv per folder)

# go into the folder listed at filelist[i]
setwd(paste0("~/Desktop/GitHub/ComputationalBiology/OppenheimerBio6100/Homework11/OriginalData","/", filelist[i]))

# get the csv data from filename
csvdata <- read.csv(filenames[i]) # read in the csv from this folder, off of the list of good csvs!
csvdata

dfcsv <- data.frame(csvdata)
dfcsv

# GETTING INFORMATION

# get rid of empty/missing cases
dfcsv <- na.omit(dfcsv[,1:20]) # rows after 20 are either all NA or no NA, so this seems prudent if I still want to have stuff to work with
dfcsv

# extract the year from the file name
year <- str_sub(filenames[i],43,46)


# calculate total individuals found
total_individuals <- nrow(dfcsv)

# calculate total number of unique species
species_richness <- length(unique(dfcsv[,12]))

 # fill in the empty vector for each csv
metadata[i,1:4] <- c(filelist[i], year, total_individuals, species_richness)
# number of items to replace is not a multiple of replacement length

  }

return(metadata)

  }

getinfo(filelist,filenames)

```

